### ISSUE TITLE
Questions about code release

### ISSUE THREAD

**Issue by byungjur96** [caiyuanhao1998/X-Gaussian#1]
Hi! I've just read your fabulous research, and I really want to run some test with your code for my task.
When will the code be released?
I'm really fascinated to run your code.
Thanks for sharing your fantastic research result!

**Comment by caiyuanhao1998** [comment]
Thanks for your interest. Our paper is in submission. We will release the code and models after the acceptance of our paper. Stay tuned.

**Comment by byungjur96** [comment]
Thanks! And I wish you a best luck for your submission

**Comment by jaykshirsagar05** [comment]
Hey there, Authors! Just wanted to express my gratitude for the fantastic work. I'm really looking forward to trying out your architecture with my X-ray angiography data. Any news on when you'll be releasing the code? Thanks!

**Comment by caiyuanhao1998** [comment]
Hi, code for X-Gaussian will be released after the acceptance of our paper. But maybe you can use the code of our another work [SAX-NeRF](https://github.com/caiyuanhao1998/SAX-NeRF). It was just released and it is also about X-ray 3D reconstruction :)

**Comment by byungjur96** [comment]
Thanks for the notification! I was also waiting for code release of your fantastic work SAX-NeRF. Thanks again :)

**Comment by caiyuanhao1998** [comment]
Thanks for your interest and patience. If you find SAX-NeRF useful, please help us star it. Thanks :)

**Comment by caiyuanhao1998** [comment]
Hi, code havs been released. Welcome to have a try :)
