### ISSUE TITLE
Code for Reconstruction Evaluation?

### ISSUE THREAD

**Issue by ecoArcGaming** [caiyuanhao1998/X-Gaussian#10]
Hi,

Is the code where SART, ASD-POCS, and FDK were used to evaluate the CT reconstruction available? I would like to test the model on some custom datasets.

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

I released the code of SART, ASD-POCS, and FDK at our CVPR 2024 work repo:

https://github.com/caiyuanhao1998/SAX-NeRF/

Feel free to check them.

If you find our repo useful, please help us star it, thanks :)
