### ISSUE TITLE
Novel Views at Additional Camera Angles?

### ISSUE THREAD

**Issue by ecoArcGaming** [caiyuanhao1998/X-Gaussian#11]
Hi, how do I use to model to render views from custom camera angles that are not seen in training? Couldn't find any scripts in this or the SAX-NeRF repo.

**Comment by caiyuanhao1998** [comment]
Yeah, you need to write the code to implement this part :)

**Comment by caiyuanhao1998** [comment]
The testing code contains the testing views. But if you want to customize, you need to write the code
