### ISSUE TITLE
How to get the intrinsic

### ISSUE THREAD

**Issue by ansj11** [caiyuanhao1998/X-Gaussian#14]
I want to know how to calculate the intrinsic? Could the 3DGS optimize the extrinsics and intrinsics at the same time？

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

The extrinsics and intrinsics are computed by the parameters of the X-ray scanner in `scene/dataset_readers.py` Line 318 - 373.

https://github.com/caiyuanhao1998/X-Gaussian/blob/master/scene/dataset_readers.py#L318

If you find our repo useful, please help us star it.

**Comment by leejngmn** [comment]
> Hi, thanks for your interest.
> 
> The extrinsics and intrinsics are computed by the parameters of the X-ray scanner in `scene/dataset_readers.py` Line 318 - 373.
> 
> https://github.com/caiyuanhao1998/X-Gaussian/blob/master/scene/dataset_readers.py#L318
> 
> If you find our repo useful, please help us star it.

Thank you for your kind reply. 
So are extrinsics and intrinsics calculated for each CT slice image? For what?
