### ISSUE TITLE
GIF looks strange

### ISSUE THREAD

**Issue by dfdu233** [caiyuanhao1998/X-Gaussian#16]
Hi, I was doing experiments on chest_50.picke.

**The results is perfect**
[ITER 20000] Evaluating test: SSIM = 0.9998824644088745, PSNR = 45.2349471282959
2024-10-03 08:36:39,366 - INFO: Iter:20000, total_points:311565

**But the gif looks really strange**

![chest_fps_30](https://github.com/user-attachments/assets/ad8db7cf-4b28-46a8-ba49-767afb4c7cfa)

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

You need to tweak the hyperparameters to get good visual performance, for example, the point size, imaging range (the box), etc.

Hope this information help you :)
