### ISSUE TITLE
About computations of DRR

### ISSUE THREAD

**Issue by tlxhlll** [caiyuanhao1998/X-Gaussian#17]
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/4dd0a458-4eb4-4122-bd41-82bef1b7f99e">
Hi! In your paper, you said DRR has lower computation cost than RGB rasterization in 3DGS. But I see the computation process looks like the process in 3dgs. How do you get the conclusion?

**Comment by caiyuanhao1998** [comment]
If you run the original 3DGS, you must switch to their rasterizer and settings instead of mine. Also, you must switch to the original SfM for initialization instead of directly using mine init. Then you can tell which one is faster.
