### ISSUE TITLE
Comparison to SAX-NeRF

### ISSUE THREAD

**Issue by dveni** [caiyuanhao1998/X-Gaussian#2]
Hi! 
Very neat project, do you have numbers of how does it compare with your SAX-NeRF work?
Looking forward to the code release (:

**Comment by caiyuanhao1998** [comment]
Yes, but SAX-NeRF was just accepted recently. It has not been published formally. So it is not necessary to compare with it in our X-Gaussian paper. 

Our paper is in submission now. We will release the code and models after the acceptance. Stay tuned

**Comment by caiyuanhao1998** [comment]
Hi, code havs been released. Welcome to have a try :)
