### ISSUE TITLE
About Radiation Intensity Response Function (RIRF)

### ISSUE THREAD

**Issue by xiangcai8** [caiyuanhao1998/X-Gaussian#20]
Hi !
In your paper, you said that you present a Radiation Intensity Response Function (RIRF) to replace the SH function of the original 3DGS. 
<img width="804" alt="RIRF" src="https://github.com/user-attachments/assets/9f3635a7-3b8d-4a7f-97c5-cf39a9f81ba6">
However, I couldn’t find where it’s implemented in your code, especially regarding the feature vector f and constant weights λ.  Could you tell me where it is?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

RIRF is implemented in the cuda_rasterizer

ACUI is implemented in the dataloader:
https://github.com/caiyuanhao1998/X-Gaussian/blob/master/scene/dataset_readers.py#L412
