### ISSUE TITLE
camera.json 

### ISSUE THREAD

**Issue by leejngmn** [caiyuanhao1998/X-Gaussian#21]
Hello. 
Thank you for your awesome research. 

1. What does camera.json generated in the output file mean? 
Is it related to CT slice images or random camera poses?

2. I wonder what id and img_name in camera.json mean.
Is the img here saved separately? Is it a CT slice image in the raw data?

3. What are the extrinsic parameters input to X-Gaussian?

**Comment by caiyuanhao1998** [comment]
1. It is related to the camera poses

2. mean the image index. The projection images are stored in the pickle file

3. the camera-to-world matrices of the view points
