### ISSUE TITLE
Which parts of the code were modified from 3DGS?

### ISSUE THREAD

**Issue by Noob-PeNguiN** [caiyuanhao1998/X-Gaussian#23]
Greetings.

I've been studying your code, and trying to make some modifications to it. I wonder what modifications are made to the original 3DGS code in your code? 

As far as I've noticed:
1. In `/scene/dataset_readers/` you've added some functions for the **ACUI** process.

2. In the forward.cu in `/submodules/diff-gaussian-rasterization/` you remove the x,y,z when computing the color from SH. And in backward.cu, you delete the gradients that are relevant to the direction. I'm guessing it's how you implement your **Radiative Gaussian Point Cloud** model? Because I see no modification in class `GaussianModel_Xray` in `/scene/gaussian_model/`, it looks exactly like the `GaussianModel` class in the original 3DGS source code except for some comments. 

I'm worried if I missed something hence I commit this issue.  By the way, I also wonder how I can get novel view synthesis pictures like the ones in Fig.5 in the paper.

Really appreciate your time to read this and looking forward to your reply.

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

Yes, the main modifications are in cuda rasterizer and ACUI.

cuda rasterization uses RIRF to render the Xray intensity and ACUI enables our model SfM-free, which significantly accelerate the speed of our model
