### ISSUE TITLE
How I can train the model with my own data?

### ISSUE THREAD

**Issue by Noob-PeNguiN** [caiyuanhao1998/X-Gaussian#24]
Greetings.
I wonder how I can train the model with my own data. I've noticed that you've serialized your data with Pickle and I'm not 100% sure how I should degisn the class for my data such that it'll fit in the training process well.
Really appreciate your time to read this and looking forward to your reply.

**Comment by caiyuanhao1998** [comment]
Hi, I did not serialize the projections. I suggest you use our data generation code in our CVPR 2024 work SAX-NeRF:

https://github.com/caiyuanhao1998/SAX-NeRF/

to synthesize the projections and then train on your data.
