### ISSUE TITLE
About size of point clouds

### ISSUE THREAD

**Issue by shenao1994** [caiyuanhao1998/X-Gaussian#25]
Hello! I have implemented 3DGS reconstruction of lumbar vertebrae using your code. However, I found that the reconstructed point cloud size is inconsistent with the original CT size, as shown in the following figure. (The red point cloud is the reconstructed 3DGS, and the gray point cloud is the original volume.)I checked the code for initializing the point cloud size and found that it is consistent with the original size. I hope to receive your reply, thank you!
![微信截图_20241014181554](https://github.com/user-attachments/assets/58b0942b-1ae1-4815-9efa-9117a2920590)
![微信截图_20241014181613](https://github.com/user-attachments/assets/b7cb6e0f-b70f-4340-89b0-3c09309e1ded)
![微信截图_20241014181620](https://github.com/user-attachments/assets/9d735c25-9bb0-4a95-b625-b27e5f06bfb6)
![微信截图_20241014181705](https://github.com/user-attachments/assets/355640b7-28a4-4708-adf7-1fb8b50b0a4c)

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

This is because of the initialization. I give your two suggestions,

First, enlarge the initialization bounding box, e.g., from 256x256x256 to 512x512x512

Second, increase the number of initialization point clouds.

**Comment by shenao1994** [comment]
> Hi, thanks for your interest,
> 
> This is because of the initialization. I give your two suggestions,
> 
> First, enlarge the initialization bounding box, e.g., from 256x256x256 to 512x512x512
> 
> Second, increase the number of initialization point clouds.

I tried the improvement method you suggested, setting the interval to 2 and doubling the size of the voxel. However, after the experiment, it was found that the size of the vertebrae did not change, only the volume of the entire 3dgs point cloud increased, as shown in the figure(The red point cloud is the reconstructed 3DGS, and the green point cloud is the original volume).
![微信截图_20241015103034](https://github.com/user-attachments/assets/0eb22e12-83a2-4134-829c-252f87788cd3)

Do I think it's related to the parameters of the camera? Or can it be said that the reconstruction of 3dgs relies entirely on 2D images, without the constraints of 3D information, and cannot generate a 3D model that is completely consistent with the original size?

My idea is to first initialize the point cloud using CT combined with the marching cubes algorithm, and then train the parameters of 3dgs.

I hope to receive your reply, thank you!
