### ISSUE TITLE
HDR-GS

### ISSUE THREAD

**Issue by deism** [caiyuanhao1998/X-Gaussian#26]
I am curious if HDR-GS can accelerate view synthesis of this project? Your new paper shows it achieves 1000x faster inference speed compared to traditional methods like NeRF, making it highly efficient for rendering novel HDR views and reconstructing LDR images.

**Comment by caiyuanhao1998** [comment]
Hi, the 1000x speed is compared to NeRF-based method, but our X-Gaussian is based on 3DGS. It is already 73x faster than previous NeRF-based algorithms.
