### ISSUE TITLE
Question about Xray_readCamerasFromTransforms_addtional

### ISSUE THREAD

**Issue by Noob-PeNguiN** [caiyuanhao1998/X-Gaussian#29]
Greetings.
I've found that when reading data in Xray_readNerfSyntheticInfo(), it creates additional camera poses using Xray_readCamerasFromTransforms_addtional(). But in this function, the variable projs is a matrix filled with zeros. I wonder why is this reasonable, because after randomly generating a new angle, when observing the image from this angle, there should still be something in the image instead of a completely empty image? Wouldn't this hinder the model's understanding of the image?
Really appreciate your time to read this and looking forward to your reply.

**Comment by caiyuanhao1998** [comment]
Because we do not have the projections for the additional poses

**Comment by Noob-PeNguiN** [comment]
yes, but is it ok to just set it to zero matrix？
