### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by aqsa4321** [caiyuanhao1998/X-Gaussian#31]
How are you calculating the final metrics? The rendering and metrics codes from Gaussian splatting give different values than you claimed in your paper. I believe you are using different ways to calculate the evaluation metrics. Please let me know. Thank you!

**Comment by caiyuanhao1998** [comment]
Hi, the results reported in the paper are exactly the same as in our repo. Please refer to our training log.

If you find our repo useful, please help us star it. Thanks.
