### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by leejngmn** [caiyuanhao1998/X-Gaussian#6]
Hello! 
I appreciate your research.
Your research has led to some interesting collaborations. 

I am trying to run X-Gaussian on CT data from another research team. 
Should I refer to SAX-NeRF dataGenerator? 
I am curious about the steps required to use Customdataset with X-Gaussian.

Also, when I use SAX-NeRF's data_vis_.py, I get the following error. 
Is there an option that I need to set when exporting the raw file?

Traceback (most recent call last):
  File "data_vis_toy.py", line 19, in <module>
    raw_data_vis = raw_data.reshape(256, 256, 256)
ValueError: cannot reshape array of size 6223036416 into shape (256,256,256)

**Comment by caiyuanhao1998** [comment]
Hi, thansk for your interest

Yes, please use the data generation code provided by SAX-NeRF (please also consider giving it a star, thank you), and then use the pickle processing code to re-dump the pickle data.

You need to modify the parameters in the data visualization code to adapt to the data to be visualized.
