### ISSUE TITLE
Questions About GaussianModel_Xray and Reconstruction 

### ISSUE THREAD

**Issue by JachyLikeCoding** [caiyuanhao1998/X-Gaussian#7]
Hello,

I am very interested in your X-Gaussian work, and I have a few questions related to it:

(1) The "GaussianModel_Xray" in the code seems to be identical to the original "GaussianModel", and I don't see changes related to "density" in the X-ray scene. Additionally, it looks like "radiodensity_lr" parameter and "alpha_to_density" function are not being used. Could you please clarify the reason for this?

(2) I noticed in a previous issue that you mentioned R^2-Gaussian can achieve volume reconstruction for CT. Could you share when this project might be open-sourced?

Looking forward to your response!

Thank you!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your inetrests.

(i) We modify the point feature part. And we also give up using SH function. Please refer to the rasterization code and data preprocssing code.

(ii) Code will be released after the paper is accepted. Please stay tuned.

If you find our repo useful, please help us star it, thank you :)
