### ISSUE TITLE
ImportError: cannot import name 'GaussianModel' from 'gaussian_renderer' (X-Gaussian/gaussian_renderer/__init__.py)

### ISSUE THREAD

**Issue by ecoArcGaming** [caiyuanhao1998/X-Gaussian#8]
Hi,

Is render.py the code used to synthesize novel views once the model is trained? I am getting this error when trying to run the file. Seems like a bug, but I could also be running the wrong file.

Would also appreciate some documentation on rendering x-rays at different camera angles. Thanks.

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest!

Yes, the render.py should be the testing code in the original 3DGS, but it should be modified before using it.

Since I did not use this code, I suggest you follow our instruction to train and test.

If you find our repo useful, please help us star it, thanks :)

**Comment by ecoArcGaming** [comment]
But full_eval.py seems to be calling render.py. How do I evaluate something using the trained model if render.py doesn't work?
