### ISSUE TITLE
question about the projection mode

### ISSUE THREAD

**Issue by ljh12401** [caiyuanhao1998/X-Gaussian#9]
hello, thanks for your great work!
i was wondering what kind of projection mode did you use in your paper, center projection or parallel projection?  In my opinion the x-ray photos are taken in parallel projection.
thanks again and looking forward to your reply!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

The x-ray mode we used is cone-beam shape. I guess it belongs to the center projection. All x-rays converge to the source. You can refer to the figure of the camera system in the `README.MD` file.

If you find our repo useful, please help us star it, thanks:)

**Comment by ljh12401** [comment]
thanks a lot
